# Generated by Django 6.0 on 2026-01-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("excerpt", models.TextField()),
                ("content", models.TextField(blank=True)),
                ("author", models.CharField(default="BuildWithSharma", max_length=100)),
                ("date", models.DateField()),
                ("read_time", models.CharField(max_length=20)),
                ("category", models.CharField(max_length=100)),
                ("image", models.URLField(blank=True, max_length=500)),
                ("featured", models.BooleanField(default=False)),
                ("slug", models.SlugField(max_length=300, unique=True)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
