# Generated by Django 6.0 on 2026-01-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Backend", "Backend"),
                            ("Frontend", "Frontend"),
                            ("CMS", "CMS"),
                            ("Website Builder", "Website Builder"),
                            ("Static Sites", "Static Sites"),
                            ("Cloud", "Cloud"),
                            ("Database", "Database"),
                            ("DevOps", "DevOps"),
                            ("CI/CD", "CI/CD"),
                            ("Marketing", "Marketing"),
                        ],
                        max_length=50,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Technologies",
                "ordering": ["order", "name"],
            },
        ),
    ]
